### PR TITLE
Add an introduction to the README.md

### PR DESCRIPTION
**Pull request by johanesrafael**
Add some paragraph to the README.md to explain ...
Also add a heading ...

### CODE REVIEW

**Comment by okkhoy** [comment]
IF this is your submission for this week's IP task, please edit the title to follow the specified convention: https://nus-cs2113-ay2021s1.github.io/website/schedule/week4/project.html#1-create-a-pr-to-the-upstream-repo-mon-aug-31st-2359
If this PR was done by mistake, please close it and make another PR as specified.

**Comment by okkhoy** [comment]
@johanesrafael for your action, please

**Comment by johanesrafael** [comment]
Dear Prof.Akshay Narayan,
I have closed that particular PR.
It was done by mistake. However, I have provided this week's IP earlier
[Johanes Rafael Sudardji] iP #17
My apology and thank you for informing me.

Best regards,
Johanes Rafael

**Comment by okkhoy** [comment]
No worries! thanks for the prompt action

**Pull request closed without merging**
